# Generated by Django 5.2 on 2025-04-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('task_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
